[package]
name = "sokoban-generator"
version = "0.1.0"
authors = ["Azleur <ribonucleasa@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.3"
rand_pcg = "0.2.1"
crossterm = "0.17.7"